variables:
- group: "production"

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - api

pool:
  vmImage: ubuntu-latest

jobs:
- job: CI
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: |
      if [ -f extensions.csproj ]
      then
          dotnet build extensions.csproj --runtime ubuntu.16.04-x64 --output ./bin
      fi
    displayName: 'Build extensions'
    workingDirectory: 'api'
  - script: |
      npm install
      npm run build:production
    displayName: 'Prepare binaries'
    workingDirectory: 'api'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'api/api.zip'
      publishLocation: 'pipeline'
      artifact: 'api'

- deployment: CD
  dependsOn: CI
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  environment: 'Azure'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureFunctionApp@1
          displayName: 'Azure Functions App Deploy'
          inputs:
            azureSubscription: '$(azureSubscription)'
            appType: 'functionAppLinux'
            appName: '$(functionAppName)'
            package: '$(Pipeline.Workspace)/api/api.zip'
            runtimeStack: 'NODE|16'
